=== OrchidRock/MimiQQ/xmld/mimiqq.dtd
<!ELEMENT mimiqq (login|loginback|signin|signinback|record
					|recordreq|recordreqback|search|searchback
					|CRA|friendadd|flocknumber|frienddelete
					|flockcreate|flockdelete|flocknumbersreq
					|flocknumbersreqback|getonlineuserap		
				        |getonlineuserapback|exit)>
<!ATTLIST mimiqq xmlns CDATA #FIXED "www.orchid.party/mimiqq">
<!-- login -->
<!ELEMENT login (user)>

<!-- user -->
<!ELEMENT user (uid,(password)?,(nickname,email,imageurl)?,
				(onlinestate)?,(ipaddress,openport)?)>
<!ELEMENT uid (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT ipaddress (#PCDATA)>
<!ELEMENT openport (#PCDATA)>
<!ELEMENT nickname (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT imageurl (#PCDATA)>

<!-- loginback -->
<!ELEMENT loginback (user,(friendlist)?,(flocklist)?,(crabacklist)?)>
<!ELEMENT friendlist (listlength,(friend)+)>
<!ELEMENT flocklist (listlength,(flock)+)>
<!ELEMENT crabacklist (listlength,(craback)+)>
<!ELEMENT listlength (#PCDATA)>

<!-- friend -->
<!ELEMENT friend (user,(groupname,remark)?,hassession)>
<!ELEMENT onlinestate (#PCDATA)>
<!ATTLIST onlinestate olstype (Y|N) "Y">
<!ELEMENT groupname (#PCDATA)>
<!ELEMENT remark (#PCDATA)>
<!ELEMENT hassession (#PCDATA)>
<!ATTLIST hassession hstype (Y|N) "Y">

<!-- flock -->
<!ELEMENT flock ((fid)?,name,createrid,createdate,imageurl,notes)>
<!ELEMENT fid (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT createrid (#PCDATA)>
<!ELEMENT createdate (#PCDATA)>
<!ELEMENT notes (#PCDATA)>

<!-- cra -->
<!ELEMENT cra (ownerid,targetid,notes,action)>
<!-- craback -->
<!ELEMENT craback (ownerid,targetid,notes,state)>

<!ELEMENT ownerid (#PCDATA)>
<!ELEMENT targetid (#PCDATA)>
<!ATTLIST targetid type (user|flock) "user">
<!ELEMENT state (#PCDATA)>
<!ELEMENT action (#PCDATA)>
<!ATTLIST action actiontype (new|setok|setfailed|delete) "new">

<!-- signin -->
<!ELEMENT signin (user)>

<!-- signinback -->
<!ELEMENT signinback (uid)>

<!-- recordreq -->
<!ELEMENT recordreq (ownerid,targetid,beforeday) >
<!ELEMENT beforeday (#PCDATA)>

<!-- recordreqback -->
<!ELEMENT recordreqback (recordlist,(beforeday)?)>
<!ELEMENT recordlist (listlength,(record)*)>

<!-- record -->
<!ELEMENT record (ownerid,(ipaddress,openport)?,targetid,recorddate,data)>
<!ATTLIST record recordtype (MESSAGE|PICTURE|FILE|IAMBACK|
		GOODBAY|BREAKOFF|SEEHERE|IAMQUIT|HESHEJOIN|
		CRA_HELLO|CRA_OK|CRA_FAILED) "MESSAGE">

<!ELEMENT recorddate (#PCDATA)>
<!ELEMENT data (#PCDATA)>

<!-- search -->
<!ELEMENT search (searchkey)>
<!ELEMENT searchkey (#PCDATA)>

<!-- signinback -->
<!ELEMENT searchback ((userlist)?,(flocklist)?)>
<!ELEMENT userlist (listlength,(user)+)>

<!-- CRA -->
<!ELEMENT CRA (cra)>

<!-- friendadd -->
<!ELEMENT friendadd (uid,friend)>

<!-- flocknumber -->
<!ELEMENT flocknumber (fid,uid,operator)>
<!ELEMENT operator (#PCDATA)>
<!ATTLIST operator optype (add|new) "add">

<!-- frienddelete -->
<!ELEMENT frienddelete (ownerid,targetid)>

<!-- flockcreate -->
<!ELEMENT flockcreate (flock)>

<!-- flockdelete -->
<!ELEMENT flockdelete (fid)>

<!-- flocknumbersreq -->
<!ELEMENT flocknumbersreq (fid)>

<!-- flocknumbersreqback -->
<!ELEMENT flocknumbersreqback (fid,userlist)>

<!-- getonlineuserap -->
<!ELEMENT getonlineuserap (uid)>

<!-- getonlineuserapback -->
<!ELEMENT getonlineuserapback (user)>

<!-- exit -->
<!ELEMENT exit (uid,(friendlist)?)>

=== OrchidRock/MimiQQ/xmld/recordreqback.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mimiqq SYSTEM "xml/mimiqq.dtd">
<mimiqq xmlns="www.orchid.party/mimiqq">
	<recordreqback>
		<recordlist>
			<listlength>2</listlength>
			<record recordtype="MESSAGE">
				<ownerid>1058712592</ownerid>
				<targetid type="user">10000000</targetid>
				<recorddate>16-05-27 22:41:14</recorddate>
				<data>I Love you</data>
			</record>
			<record recordtype="MESSAGE">
				<ownerid>10000000</ownerid>
				<targetid type="user">1058712592</targetid>
				<recorddate>16-05-27 22:42:14</recorddate>
				<data>I Love you,too</data>
			</record>
		</recordlist>
		<beforeday>0.1</beforeday>
	</recordreqback>
</mimiqq>

=== OrchidRock/MimiQQ/xmld/searchback.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mimiqq SYSTEM "xml/mimiqq.dtd">
<mimiqq xmlns="www.orchid.party/mimiqq">
<searchback>
	<userlist>
		<listlength>2</listlength>
		<user>
			<uid>1058712592</uid>
			<nickname>Rock</nickname>
			<email>123</email>
			<imageurl>rock.png</imageurl>
			<onlinestate olstype="N"/>
		</user>
		<user>
			<uid>100000001</uid>
			<nickname>puppy</nickname>
			<email>123456</email>
			<imageurl>puppy.png</imageurl>
			<onlinestate olstype="Y"/>
		</user>
	</userlist>
	<flocklist>
		<listlength>1</listlength>
		<flock>
			<fid>Linux</fid>
			<name>LL</name>
			<createrid>1058712592</createrid>
			<createdate>123</createdate>
			<imageurl>ll.png</imageurl>
			<notes>Hello,Linux os</notes>
		</flock>
	</flocklist>
</searchback>
</mimiqq>

=== OrchidRock/MimiQQ/xmld/loginback.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mimiqq SYSTEM "xml/mimiqq.dtd">
<mimiqq xmlns="www.orchid.party/mimiqq">
	<loginback>
		<user>
		    <uid>1058712592</uid>
			<nickname>Rock</nickname>
			<email>rocksevencolor@gmail.com</email>
			<imageurl>rock.png</imageurl>
		</user>
		<friendlist>
		    <listlength>1</listlength>
			<friend>
			    <user>
					<uid>10000000</uid>
					<nickname>Puppy</nickname>
					<email>1058712592@qq.com</email>
					<imageurl>puppy.png</imageurl>
					<onlinestate olstype="Y"/>
					<ipaddress>127.0.0.1</ipaddress>
					<openport>8800</openport>
				</user>
				<hassession hstype="Y"/>
			</friend>
		</friendlist>
		<flocklist>
			<listlength>1</listlength>
			<flock>
				<fid>10000001</fid>
				<name>Linux</name>
				<createrid>1058712592</createrid>
				<createdate>2016-5-27 22:57</createdate>
				<imageurl>linux.png</imageurl>
				<notes>Hello,Linux os</notes>
				</flock>
		</flocklist>
		<crabacklist>
			<listlength>2</listlength>
			<craback>
				<ownerid>1058712592</ownerid>
				<targetid type="flock">10000001</targetid>
				<notes>I want join in yours</notes>
				<state statetype="waiting" />
			</craback>
			<craback>
				<ownerid>1058712592</ownerid>
				<targetid type="flock">10000001</targetid>
				<notes>I want join in yours</notes>
				<state statetype="ok" />
			</craback>
		</crabacklist>
		<recordlist>
			<listlength>0</listlength>
		</recordlist>
	</loginback>
</mimiqq>
